---
title: "Meta-analysis of the rodent object-in-context task: MetaForest Follow-up PD and WS plots"
author: "Milou Sep"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

## Metaforest follow-up plots of top 50% most important variables
https://www.rdocumentation.org/packages/metaforest/versions/0.1.3

# Load packages
```{r setup, include=FALSE}
rm(list = ls()) #clean environment
# packages
library(metaforest) #for exploratory analysis
# visualizations
library(ggplot2) 
library(ggpubr) # https://rpkgs.datanovia.com/ggpubr/reference/ggarrange.html
library(gtable)
library(grid)
# to check which packages are loaded
# (.packages())
```

# Load data
```{r metaforest varimportance scores}
readRDS(file="processed_data/fitted.MetaForest.RDS")->cv.mf.cluster
readRDS(file="processed_data/datForest_for_WS_Plot.RDS")->datForest_for_WS_Plot
readRDS(file="processed_data/important_variables.RDS")->variable # Top 50% important variables
variable
```

# Partial Dependence plots
Some info on PD plots: https://cjvanlissa.github.io/metaforest/articles/Introduction_to_metaforest.html
- “partial dependence plots” display the predicted effect size at different levels of a specific moderator, whilst averaging over all other moderators.
```{r metaforest PD plots}
PartialDependence(cv.mf.cluster$finalModel, vars = variable, moderator = "Species", bw =F, rawdata = F, output = "list")->PD.list

# Manual layout changes to PD.list (all plots)
for(i in 1:length(PD.list)){
  PD.list[[i]]$theme$axis.title.y = element_blank()
  PD.list[[i]]$labels$y = "mean DR"
  PD.list[[i]][["theme"]][["legend.position"]] = c(1,0)
  PD.list[[i]][["theme"]][["legend.justification"]] = c("right", "bottom") #c(1, 0) # change corner
}

# Manual layout changes to PD.list (change x-axis horizontally for some plots)
for(m in c(2,3,5, 7,8,17)){
  PD.list[[m]]$theme$axis.text.x = element_text(angle = 0,hjust = 1,vjust = 1)
}

# The code below is a copy of the merge_plots() function from the PartialDependence() function in MetaForest. This code is derived from the PartialDependence() source code and used to merge the PD plots after the manual layout changes above.
merge_plots <- function(plots, ...){
  args <- match.call()
  if(!("ylab" %in% names(args))){
    ylab <- plots[[1]]$labels$y
  }
  n_grobs <- length(plots)
  grob_rows <- floor(sqrt(n_grobs))
  grob_cols <- ceiling(sqrt(n_grobs))
  if((grob_rows*grob_cols) < n_grobs){
    grob_rows <- grob_rows + 1
  }
  for(x in 1:length(plots)){
    if(!(x %in% seq.int(1, n_grobs, by = grob_cols))){
      plots[[x]] <- plots[[x]] + theme(axis.text.y = element_blank(),
                                       axis.ticks.y = element_blank())
    }
    if(!x == grob_cols){
      plots[[x]] <- plots[[x]] + theme(legend.position = "none")
    }
    plots[[x]] <- suppressMessages(ggplotGrob(plots[[x]]+theme(axis.title.y = element_blank())))
    if(x > 1) plots[[x]]$widths <- plots[[1]]$widths
  }
  
  if(n_grobs < (grob_cols * grob_rows)){
    plots[(length(plots)+1):(grob_cols * grob_rows)] <- lapply((length(plots)+1):(grob_cols * grob_rows), function(x){nullGrob()})
  }
  
  gt <- gtable_matrix("partial.dependence",
                      matrix(plots, nrow = grob_rows, byrow = TRUE),
                      widths = unit(rep(1, grob_cols), "null"),
                      heights = unit(rep(1, grob_rows), "null"))
  
  left <- textGrob(ylab, rot = 90, just = c(.5, .5))
  gt <- gtable_add_cols(gt, widths = grobWidth(left)+ unit(0.5, "line"), 0)
  gt <- gtable_add_grob(gt, left, t = 1, b = nrow(gt),
                        l = 1, r = 1, z = Inf)
  gt <- gtable_add_cols(gt, widths = unit(0.5, "line"))
  
  grid.newpage()
  grid.draw(gt)
  invisible(gt)
}

#combine plots and save figure
{ jpeg(file="results/metaforest_adapted_PD_plots.jpeg", height = 6000, width = 8000, res=500)
  merge_plots(PD.list)
  dev.off()
}
```


# Weighted Scatter plots
Some info on WS plots: https://t-redactyl.io/blog/2016/02/creating-plots-in-r-using-ggplot2-part-6-weighted-scatterplots.html
```{r metaforest weighted scatter}
WS_plots = function (data, variable) {
  ggplot(data, 
         aes_string(x = variable, y = "yi", colour = "Species", size="nC"))+
    geom_jitter(width=0.1, alpha=0.5) +
    theme_bw()+
    labs(y = "DR",
         size = "Sample size") +
    scale_size(range = c(0.1, 5)) #http://www.rebeccabarter.com/blog/2017-11-17-ggplot2_tutorial/
}

WS_plotlist <- lapply(variable, WS_plots, data = datForest_for_WS_Plot)

# Change x-axis horizontally
for(m in c(2,3, 5, 7,8,17)){
  WS_plotlist[[m]]$theme$axis.text.x = element_text(angle = 0,hjust = 1,vjust = 1)
}

# combine WS plots
ggarrange(plotlist=WS_plotlist, widths = c(5,5),
          align = "v",
          common.legend = T#, labels = c("a", "b")
)
# save WS plots
ggsave("results/metaforest_adapted_WS plots.jpeg", device = "jpeg", height = 12, width = 15, dpi=400)
```